### ISSUE TITLE
Wildcards being replaced (useful for monorepos)

### ISSUE THREAD

**Issue by zomars** [JamieMason/syncpack#92] opened 2022-08-12 22:18 UTC
## Description

Monorepo packages that uses wildcard versions `"example": "*"` are being replaced by `"example": "0.0.0"`

## Suggested Solution

Leave as it is?

## Help Needed

Is there a way to prevent this? Couldn't find anything in the README about this.

**Comment by JamieMason** [comment] 2022-08-12 22:28
It sounds like defining a server group might be what you need, this would let you define which packages should only use *

https://github.com/JamieMason/syncpack#semvergroups

**Comment by zomars** [comment] 2022-08-12 23:13
Tried adding this config but no luck still:

```
"semverGroups": [
      {
        "range": "~",
        "dependencies": ["@alpha/**"],
        "packages": ["**"]
      }
    ]
```

Still `"@alpha/example": "*"`  is being transformed to `"@alpha/example": "0.0.0"`

**Comment by zomars** [comment] 2022-08-12 23:17
Adding a custom filter works for now: 

```
    "filter": "^(?!@alpha).*",
```

**Comment by JamieMason** [comment] 2022-08-13 06:27
If you can share a reproduction I can take a look for you

**Comment by JamieMason** [comment] 2022-10-28 13:09
Closing as blocked but please reopen with a repro if you find the time.

**Closed by JamieMason** 2022-10-28 13:09 UTC
Labels: Status: Blocked, Type: Question, Status: With Author

**Comment by JamieMason** [comment] 2022-10-28 17:05
Actually, have a check with [8.3.9](https://github.com/JamieMason/syncpack/releases/tag/8.3.9) – I found that support for setting versions to `'*'` wasn't available in any circumstances. All other ranges were supported.

**Comment by macieklad** [comment] 2022-11-11 15:32
Hi, it seems that support for * is still broken with 8.3.9, i have created a simple repro, just run `yarn syncpack` and versions will be set to 0.0.0. 

https://github.com/macieklad/syncpack-repro

**Comment by JamieMason** [comment] 2022-11-24 21:40
I don't know what commands you guys are running (whether they're the version-related commands or the semver range commands) but looking at https://github.com/macieklad/syncpack-repro @macieklad I think the problem is that [workspace is enabled by default](https://github.com/JamieMason/syncpack#dev-peer-prod-resolutions-overrides-pnpmoverrides-and-workspace), so it is using the versions of your own packages as the source of truth for what should be the correct version for them when they are used as a dependency. 

If you set `workspace: false` in your `/syncpack.config.js` it should hopefully work as you're expecting. Give that a try @macieklad @zomars and I can try and help you from there if it does not get you what you need.

Thanks.

**Comment by macieklad** [comment] 2022-11-25 14:50
That is a great clarification, I have missed that option entirely, thank you! The repo is working as intended now :>  I think your answer will clarify it for others if they will stumble upon that again.

**Comment by JamieMason** [comment] 2023-11-08 12:23
There is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide now to help with some of these things.
