### ISSUE TITLE
Add support for lerna.json

### ISSUE THREAD

**Issue by jantimon** [JamieMason/syncpack#11] opened 2018-09-07 06:48 UTC
Usually people set different globs in the lerna.json.  
For example the official lerna git repository:

https://github.com/lerna/lerna/blob/901e6d54a47151dfed3d6ed2912804b97d05c6b5/lerna.json#L2-L6

Would it be possible to use that data instead of a default glob?

**Comment by JamieMason** [comment] 2018-09-07 10:27
Nice idea, thanks. I am away for a few days but maybe sketch up a proposal for the CLI options how you'd like it to work? Thanks

**Comment by jantimon** [comment] 2018-09-07 12:55
All cli tools I know use their related configuration file even if no cli options are given.  
E.g.  
npm -> package.json
babel -> .babel.rc
lerna -> lerna.json
webpack -> webpack.config.js
typescript -> tsconfig.json

So imho the correct behaviour would be to pick up the settings from lerna.json by default.  
Unfortunately that would be a breaking change for syncpack. 🤔

**Comment by JamieMason** [comment] 2018-09-07 13:06
Sure 👍 just want to be clear we're thinking of the same thing before we go ahead.

**Comment by jantimon** [comment] 2018-10-31 12:51
Thanks @JamieMason 👍

**Comment by JamieMason** [comment] 2018-10-31 12:55
You're welcome Jan

**Comment by JamieMason** [comment] 2019-02-05 14:48
It's taken me a while to work out the cause but I've realised this change is behind some slightly undesirable behaviour @jantimon. In my project I have `"packages": ["packages/*"],` in my `lerna.json` which means that when I run eg. `syncpack format` it only formats `./packages/*` and not also `./package.json` – so I have to redefine the `--source` patterns.

Would you mind please letting me know a bit more behind your usage of syncpack that led to this issue? I don't want to undo anything you were asking for when trying to improve my own workflow.

Thanks.

**Comment by jantimon** [comment] 2019-02-07 06:33
Actually it would be nice to include the base ./package.json as well.

Usually my base package.json does not contain many dependencies but some linters

I use syncpack to reduce module duplication in lernas hoist mode.

**Comment by JamieMason** [comment] 2019-02-07 08:57
Thanks a lot @jantimon, that should be a pretty easy fix 👍

**Comment by jantimon** [comment] 2019-02-08 11:47
Thanks for your work! :)

**Comment by JamieMason** [comment] 2019-05-24 16:21
Oh, this landed in 3.4.0 😊 https://github.com/JamieMason/syncpack/blob/master/CHANGELOG.md#340-2018-10-28

**Closed by JamieMason** 2019-05-24 16:21 UTC
Labels: Type: Feat
