### ISSUE TITLE
Set specific "package.json" in the repo as main file

### ISSUE THREAD

**Issue by bombillazo** [JamieMason/syncpack#88] opened 2022-07-11 01:59 UTC
## Description

It would be great to specify one package.json file within the monorepo to act as the "main" file, meaning this file is a version driver from which all other files are resolved to. Doing so will automatically limit all other packages from raising the versions if this package.json is lower than the rest while bringing the rest to the latest version specified in this main file.

## Suggested Solution

Have a new option in the configuration/cli to specify this "main" package.json file.

**Comment by JamieMason** [comment] 2022-07-11 08:58
Hi Hector,
For the upcoming [`hoist`](https://github.com/JamieMason/syncpack/issues/7) feature there's the idea of a `--target` file and multiple `--source` files, but in the general case of syncing versions I think this idea in its current form could be unintuitive. Could you go into some more detail? Maybe a specific command for this use case would be clearer. Thanks.

**Comment by JamieMason** [comment] 2022-07-11 09:56
Closing as duplicate of #87

**Closed by JamieMason** 2022-07-11 09:56 UTC
Labels: Type: Duplicate
